title: Luke's Empire
url: https://lukesempire.com
baseurl: https://lukesempire.com
tagline: Random stuff from Luke
description: Luke's website and blog
author: Luke M
logo: /photo.jpg
locale: en_US
include:
 - _redirects

